"""
SPARKS Module 3 - PERFORM Week micro-scenario catalog.

Each scenario dict:
    num            : scenario number (unique id)
    title          : short title
    description    : what the team does
    duration_text  : original duration string
    est_minutes    : parsed expected duration in minutes (None = TBD)
    max_points     : maximum reviewer points (None = TBD)
    pillars        : list of competency pillars touched (SDL/AGL/ICA/CSL)
    scoring        : scoring approach text
    day            : scheduled day (may be empty)

Scenarios 30/31 from the source sheet were blank and are intentionally omitted.
Edit this file to adjust the catalog; the app reads from SCENARIOS on startup
and seeds any missing rows into the database.
"""

SCENARIOS = [
    {
        "num": 1,
        "title": "Deploy a COLOS Printer in your Cold Brew Coffee OT 4.0 Network",
        "description": "Setup the network configuring NICs, IP addressing scheme, routing, gateways, protocols. Configure switches, install network cables. Get the COLOS printer talking to the rest of the cold brew coffee system.",
        "duration_text": "4hrs",
        "est_minutes": 240,
        "max_points": 40,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "TBD",
        "day": "Tuesday",
    },
    {
        "num": 2,
        "title": "Troubleshoot Your Way To Communicating in your Cold Brew Coffee Network",
        "description": "Trainers break the network; the team recovers functionality using common tools: ping, trace route, print route, ARP tables, network logging, etc.",
        "duration_text": "4hrs",
        "est_minutes": 240,
        "max_points": 40,
        "pillars": ["ICA", "CSL"],
        "scoring": "10 pts per network problem solved",
        "day": "Wednesday",
    },
    {
        "num": 3,
        "title": "Master Common Sensor Troubleshooting on Your Cold Brew Coffee Packing Equip",
        "description": "Check every sensor on the can packing equipment for correct functionality. Overcome misconfiguration, calibration, I/O module, wiring, analog scaling, and PLC logic issues.",
        "duration_text": "2hrs",
        "est_minutes": 120,
        "max_points": 20,
        "pillars": ["ICA"],
        "scoring": "5 pts per sensor problem solved",
        "day": "",
    },
    {
        "num": 4,
        "title": "Deploy IO Link and Smart Sensors for Your Cold Brew Coffee System",
        "description": "Improve the CBC can packing system by deploying IO Link sensors for enriched data from your OT system.",
        "duration_text": "2hrs",
        "est_minutes": 120,
        "max_points": 20,
        "pillars": ["ICA"],
        "scoring": "All or nothing - all IO Link configuration and functionality must be complete",
        "day": "",
    },
    {
        "num": 5,
        "title": "Improve Your Cold Brew Coffee Mixer Digital Twin with NEW Functionality",
        "description": "Add a new control module to your automation code to add functionality to the CBC mixing system. Deeper experience with the software and digital twins enabling the CBC mixer.",
        "duration_text": "4hrs",
        "est_minutes": 240,
        "max_points": 40,
        "pillars": ["ICA"],
        "scoring": "10 pts for CM, 20 pts for PLC Code, 10 pts for Simulation",
        "day": "",
    },
    {
        "num": 6,
        "title": "Successfully Navigate a GIA Audit",
        "description": "Navigate a GIA audit with the GIA Whisperer. Extract proper data and documentation to provide evidence on the compliance of your digital systems.",
        "duration_text": "0.5-1hr",
        "est_minutes": 45,
        "max_points": 10,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "Scoring via Rubric",
        "day": "",
    },
    {
        "num": 7,
        "title": "Role of a Cybersecurity Leader - Escape Room",
        "description": "8 puzzles with a meta-puzzle focused on the role of a cybersecurity leader.",
        "duration_text": "1hr",
        "est_minutes": 60,
        "max_points": 10,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "All or nothing - solve final puzzle",
        "day": "",
    },
    {
        "num": 8,
        "title": "Beat the AI - Databricks Queries",
        "description": "Work with an AI agent to build data queries against the Core Data Lake using Databricks and SQL. Find the errors in the AI output to reach the proper data set.",
        "duration_text": "2hrs",
        "est_minutes": 120,
        "max_points": 20,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "All or nothing - capture the flag",
        "day": "",
    },
    {
        "num": 9,
        "title": "Unlock Your Web Server By Properly Implementing SSL Certificates",
        "description": "Work through using SSL certificates to secure web server communication and resolve a 403 error to extract critical CBC performance data.",
        "duration_text": "2hrs",
        "est_minutes": 120,
        "max_points": 20,
        "pillars": ["ICA", "CSL"],
        "scoring": "All or nothing - web server is fully functional",
        "day": "",
    },
    {
        "num": 10,
        "title": "Master Communication of Digital Topics to Leadership",
        "description": "Pick an incident, project, or audit and prepare a presentation to your PM. Unlock SPARK points by effectively and efficiently communicating your plan.",
        "duration_text": "30mins",
        "est_minutes": 30,
        "max_points": 10,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "Scoring via Rubric",
        "day": "",
    },
    {
        "num": 11,
        "title": "Mapping and Matching Escape Room",
        "description": "Partake in a mapping and matching session and unlock the proper documentation needed for a clear configuration path of your enterprise systems.",
        "duration_text": "2hrs",
        "est_minutes": 120,
        "max_points": 10,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "Scoring via Rubric",
        "day": "",
    },
    {
        "num": 12,
        "title": "Reduce Touches and Make Your Initiative SMART (Value Stream Mapping)",
        "description": "Map out all touchpoints to discover where digital solutions can streamline operations. Link points to enterprise solutions to reduce manual effort.",
        "duration_text": "2hrs",
        "est_minutes": 120,
        "max_points": 20,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "5 pts per touch elimination, 10 extra points for max",
        "day": "",
    },
    {
        "num": 13,
        "title": "Build an Automation Trace and Trend to Understand Your Equipment",
        "description": "Build an automation trace/trend with both Siemens and Rockwell. Setup, configure, and analyze to complete the escape room.",
        "duration_text": "1hr",
        "est_minutes": 60,
        "max_points": 10,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "All or nothing - fully functional trend with all details",
        "day": "",
    },
    {
        "num": 14,
        "title": "Use Python to Successfully Clean Your Data (No AI)",
        "description": "Use Python to ingest raw data, clean and standardize it, then transform and engineer it into a useful format for analysis.",
        "duration_text": "2hrs",
        "est_minutes": 120,
        "max_points": 20,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "All or nothing - file comparison to grade output",
        "day": "",
    },
    {
        "num": 15,
        "title": "Flow Data through your Enterprise to the Core Data Lake using MDF Edge",
        "description": "Use E2C services to get data flowing from OT to the Core Data Lake.",
        "duration_text": "1hr",
        "est_minutes": 60,
        "max_points": None,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 16,
        "title": "Mini Net - Python Simulated Network Analysis Using PyShark",
        "description": "Leverage a simulated network in Python and PyShark to analyze network traffic in a capture-the-flag scenario.",
        "duration_text": "1-2hrs",
        "est_minutes": 90,
        "max_points": None,
        "pillars": ["ICA", "CSL"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 17,
        "title": "Patching Escape Room",
        "description": "Work through troubleshooting and patch deployment strategies to efficiently bring your system up to compliance.",
        "duration_text": "1-2hrs",
        "est_minutes": 90,
        "max_points": None,
        "pillars": ["ICA"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 18,
        "title": "Firewall Log Analysis Capture the Flag",
        "description": "Get hands on with OneBox, collecting information about your site's firewall in a capture-the-flag exercise.",
        "duration_text": "1hr",
        "est_minutes": 60,
        "max_points": None,
        "pillars": ["ICA", "CSL"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 19,
        "title": "Leverage AI to Penetrate and Understand Black Box PLC Code",
        "description": "Leverage Nexus AI to troubleshoot the CBC Mixer code with AI assistance for faster recovery.",
        "duration_text": "1-2hrs",
        "est_minutes": 90,
        "max_points": None,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 20,
        "title": "Beat the AI - Cyber Awareness Campaign",
        "description": "Prepare a cyber awareness campaign graded by an AI agent. Beat the agent to score points.",
        "duration_text": "2hrs",
        "est_minutes": 120,
        "max_points": None,
        "pillars": ["SDL", "CSL"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 21,
        "title": "Digital Jeopardy (or Family Feud)",
        "description": "Jeopardy questions focused on roles and digital skills, sprinkled throughout PERFORM week for EXTRA points.",
        "duration_text": "30mins",
        "est_minutes": 30,
        "max_points": None,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 22,
        "title": "90 Day Digital Continuity Plan",
        "description": "Given a CBC site application inventory, create a 90 day plan to bring the entire portfolio to compliance - get to GREEN.",
        "duration_text": "1hr",
        "est_minutes": 60,
        "max_points": None,
        "pillars": ["SDL", "AGL"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 23,
        "title": "Define an Application Escape Room",
        "description": "Navigate an escape room by properly classifying applications as systems, components, applications, etc.",
        "duration_text": "1hr",
        "est_minutes": 60,
        "max_points": None,
        "pillars": ["AGL"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 24,
        "title": "Your Site is DOWN - Leverage Disaster Recovery to Get Back Up and Running",
        "description": "Properly back up and demonstrate recovery of your CBC digital systems.",
        "duration_text": "1hr",
        "est_minutes": 60,
        "max_points": None,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 25,
        "title": "OCAI Tabletop Exercise - SQL Queries",
        "description": "OCAI tabletop exercise leveraging SQL queries (description to be finalized).",
        "duration_text": "TBD",
        "est_minutes": None,
        "max_points": None,
        "pillars": ["SDL", "AGL", "ICA", "CSL"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 26,
        "title": "Application Governance Jeopardy",
        "description": "Work through a Jeopardy game with categories arranged by varying AGL related topics.",
        "duration_text": "1hr",
        "est_minutes": 60,
        "max_points": None,
        "pillars": ["AGL"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 27,
        "title": "Kahoot/Slido - AGL",
        "description": "Take Kahoot/Slido quizzes on application governance and have a live discussion with your TISL about the results.",
        "duration_text": "1hr",
        "est_minutes": 60,
        "max_points": None,
        "pillars": ["AGL"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 28,
        "title": "Application Pen Testing",
        "description": "Execute pen testing on your Cold Brew Coffee application.",
        "duration_text": "1hr",
        "est_minutes": 60,
        "max_points": None,
        "pillars": ["AGL"],
        "scoring": "TBD",
        "day": "",
    },
    {
        "num": 29,
        "title": "Aravo/iRisk Capture the Flag (TPRM)",
        "description": "Navigate Aravo and iRisk via search, capturing information about your task to reach the final conclusion and solve the challenge.",
        "duration_text": "1hr",
        "est_minutes": 60,
        "max_points": None,
        "pillars": ["AGL"],
        "scoring": "TBD",
        "day": "",
    },
]

# Default max points to use when a scenario's reviewer max is still TBD.
DEFAULT_MAX_POINTS = 20
